[[keybind]]
modes = []
exclude_modes = ["c"]
keys = [":"]
commands = ["pm c"]
desc = "Enter Command Mode"

[[keybind]]
modes = []
invalid_modes = ["i"]
keys = ["i"]
commands = ["start_change", "pm i"]
desc = "Enter Insert Mode"

[[keybind]]
modes = []
keys = ["esc"]
commands = ["commit_change", "rm"]
desc = "Pop Mode From Stack"
