# Basic Movement Keys
[[keybind]]
modes = []
keys = ["left"]
commands = ["mc -1"]
desc = "Move Left"

[[keybind]]
modes = []
keys = ["down"]
commands = ["ml 1"]
desc = "Move Down"

[[keybind]]
modes = []
keys = ["up"]
commands = ["ml -1"]
desc = "Move Up"

[[keybind]]
modes = []
keys = ["right"]
commands = ["mc 1"]
desc = "Move Right"

[[keybind]]
modes = []
keys = ["h"]
commands = ["mc -1"]
desc = "Move Left"

[[keybind]]
modes = []
keys = ["j"]
commands = ["ml 1"]
desc = "Move Down"

[[keybind]]
modes = []
keys = ["k"]
commands = ["ml -1"]
desc = "Move Up"

[[keybind]]
modes = []
keys = ["l"]
commands = ["mc 1"]
desc = "Move Right"

# Jump movements (motions)
[[keybind]]
modes = []
keys = ["w"]
commands = ['rxc (?:\\w+|[^\\w\\s]+|\\s+)(\\s?) 1 false', "gse", "sc"]
desc = "Go Word"

[[keybind]]
modes = []
keys = ["e"]
commands = ['rxc (\\w+|[^\\w\\s]+|\\s+) 1 false', "gse", "sc"]
desc = "Go Word End"

[[keybind]]
modes = []
keys = ["b"]
commands = ['rxcb (?:\\w+|[^\\w\\s]+|\\s+)(\\s?) -1 false', "gsb", "sc"]
desc = "Go Back Word"

[[keybind]]
modes = []
keys = ["shift-w"]
commands = ['rxc (?:\\s+|\\S+)(\\s?) 1 false', "gse", "sc"]
desc = "Go WORD"

[[keybind]]
modes = []
keys = ["shift-e"]
commands = ['rxc (\\s+|\\S+) 1 false', "gse", "sc"]
desc = "Go WORD end"

[[keybind]]
modes = []
keys = ["shift-b"]
commands = ['rxcb (?:\\s+|\\S+)(\\s?) -1 false', "gsb", "sc"]
desc = "Go Back WORD"

[[keybind]]
modes = []
keys = ["0"]
commands = ["slb false", "gsb", "sc"]
desc = "Goto Line Start"

[[keybind]]
modes = []
keys = ["$"]
commands = ["sle false", "gse", "sc"]
desc = "Goto Line End"

[[keybind]]
modes = []
keys = ["^"]
commands = ["sfw false", "sc"]
desc = "Goto Line End"
