[[keybind]]
modes = []
invalid_modes = ["v"]
keys = ["v"]
commands = ["pm v"]
desc = "Visual Mode"

[[keybind]]
modes = ["v"]
keys = ["left"]
commands = ["mc -1 true"]
desc = "Move Left"

[[keybind]]
modes = ["v"]
keys = ["down"]
commands = ["ml 1 true"]
desc = "Move Down"

[[keybind]]
modes = ["v"]
keys = ["up"]
commands = ["ml -1 true"]
desc = "Move Up"

[[keybind]]
modes = ["v"]
keys = ["right"]
commands = ["mc 1 true"]
desc = "Move Right"

[[keybind]]
modes = ["v"]
keys = ["h"]
commands = ["mc -1 true"]
desc = "Move Left"

[[keybind]]
modes = ["v"]
keys = ["j"]
commands = ["ml 1 true"]
desc = "Move Down"

[[keybind]]
modes = ["v"]
keys = ["k"]
commands = ["ml -1 true"]
desc = "Move Up"

[[keybind]]
modes = ["v"]
keys = ["l"]
commands = ["mc 1 true"]
desc = "Move Right"

[[keybind]]
modes = ["v"]
keys = ["w"]
commands = ['rxc (?:\\w+|[^\\w\\s]+|\\s+)(.) 1 true', "gse"]
desc = "Select Word"

[[keybind]]
modes = ["v"]
keys = ["e"]
commands = ['rxc (\\w+|[^\\w\\s]+|\\s+) 1 true', "gse"]
desc = "Select Word End"

[[keybind]]
modes = ["v"]
keys = ["b"]
commands = ['rxcb (?:\\w+|[^\\w\\s]+|\\s+)(.) -1 true', "gsb"]
desc = "Select Word Back"

[[keybind]]
modes = ["v"]
keys = ["shift-w"]
commands = ['rxc (?:\\s+|\\S+)(.) 1 true', "gse"]
desc = "Select WORD"

[[keybind]]
modes = ["v"]
keys = ["shift-e"]
commands = ['rxc (\\s+|\\S+) 1 true', "gse"]
desc = "Select WORD End"

[[keybind]]
modes = ["v"]
keys = ["shift-b"]
commands = ['rxcb (?:\\s+|\\S+)(.) -1 true', "gsb"]
desc = "Select WORD Back"

[[keybind]]
modes = ["v"]
keys = ["v"]
commands = ["sl true", "gse"]
desc = "Select Line"

[[keybind]]
modes = ["v"]
keys = ["0"]
commands = ["slb true", "gsb"]
desc = "Goto Line Start"

[[keybind]]
modes = ["v"]
keys = ["$"]
commands = ["sle true", "gse"]
desc = "Goto Line End"

[[keybind]]
modes = ["v"]
keys = ["^"]
commands = ["sfw true"]
desc = "Goto Line End"

[[keybind]]
modes = ["v"]
keys = [","]
commands = ["sc"]
desc = "Collapse Selection"

[[keybind]]
modes = ["v"]
keys = ["d"]
commands = ["gsb", "commit d", "rm"]
desc = "Delete selection"

[[keybind]]
modes = ["v"]
keys = ["esc"]
commands = ["rm", "sc"]
desc = "Collapse selection, Pop Mode"
