[[keybind]]
modes = []
keys = ["h"]
commands = ["move_cursor -1 0"]
desc = "Move Left"

[[keybind]]
modes = []
keys = ["j"]
commands = ["move_cursor 0 1"]
desc = "Move Down"

[[keybind]]
modes = []
keys = ["k"]
commands = ["move_cursor 0 -1"]
desc = "Move Up"

[[keybind]]
modes = []
keys = ["l"]
commands = ["move_cursor 1 0"]
desc = "Move Right"

[[keybind]]
modes = []
keys = ["i"]
commands = ["start_change", "change_mode i"]
desc = "Enter Insert Mode"

[[keybind]]
modes = []
keys = ["esc"]
commands = ["commit_change", "change_mode n"]
desc = "Back To Normal Mode"

[[keybind]]
modes = []
keys = ["d"]
commands = ["commit delete_chars 0 1"]
desc = "Delete Char"

[[keybind]]
modes = ["n"]
keys = ["ctrl-c"]
commands = ["quit"]
desc = "Quit"

[[keybind]]
modes = ["i"]
keys = ["backspace"]
commands = ["backspace"]
desc = "Backspace"

[[keybind]]
modes = ["n"]
keys = [";", "shift-q"]
commands = ["quit"]
desc = "Quit"

[[keybind]]
modes = []
keys = ["shift-j"]
commands = ["commit join_line 0"]
desc = "Join Line"

[[keybind]]
modes = ["i"]
keys = ["enter"]
commands = ["commit insert_newline 0"]
desc = "Insert Newline"

[[keybind]]
modes = []
keys = ["u"]
commands = ["undo"]
desc = "Undo"

[[keybind]]
modes = []
keys = ["shift-u"]
commands = ["redo"]
desc = "Undo"

[[keybind]]
modes = []
keys = ["o"]
commands = ["start_change", "insert_line 1", "change_mode i"]
desc = "Start Editing Below"

[[keybind]]
modes = []
keys = ["shift-o"]
commands = ["start_change", "insert_line 0", "change_mode i"]
desc = "Start Editing Below"

[theme]
"ui.linenum" = { fg = "#555555" }

"ts.attribute" = "yellow"

"ts.type" = "yellow"
"ts.type.enum.variant" = "teal"

"ts.constructor" = "sapphire"

"ts.constant" = "peach"
"ts.constant.character" = "teal"
"ts.constant.character.escape" = "pink"

"ts.string" = "green"
"ts.string.regexp" = "pink"
"ts.string.special" = "blue"
"ts.string.special.symbol" = "red"

"ts.comment" = { fg = "overlay2", modifiers = ["italic"] }

"ts.variable" = "text"
"ts.variable.parameter" = { fg = "maroon", modifiers = ["italic"] }
"ts.variable.builtin" = "red"
"ts.variable.other.member" = "blue"

"ts.label" = "sapphire" # used for lifetimes

"ts.punctuation" = "overlay2"
"ts.punctuation.special" = "sky"

"ts.keyword" = "mauve"
"ts.keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }

"ts.operator" = "sky"

"ts.function" = "blue"
"ts.function.macro" = "rosewater"

"ts.tag" = "blue"

"ts.namespace" = { fg = "yellow", modifiers = ["italic"] }

"ts.special" = "blue" # fuzzy highlight

"ts.markup.heading.1" = "red"
"ts.markup.heading.2" = "peach"
"ts.markup.heading.3" = "yellow"
"ts.markup.heading.4" = "green"
"ts.markup.heading.5" = "sapphire"
"ts.markup.heading.6" = "lavender"
"ts.markup.list" = "teal"
"ts.markup.list.unchecked" = "overlay2"
"ts.markup.list.checked" = "green"
"ts.markup.bold" = { fg = "red", modifiers = ["bold"] }
"ts.markup.italic" = { fg = "red", modifiers = ["italic"] }
"ts.markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"ts.markup.link.text" = "lavender"
"ts.markup.link.label" = "sapphire"
"ts.markup.raw" = "green"
"ts.markup.quote" = "pink"

"ui.text" = "text"

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
