# Contains all deletion motions
[[keybind]]
modes = ["i"]
keys = ["backspace"]
commands = ["backspace"]
desc = "Backspace"

[[keybind]]
modes = []
keys = ["x"]
commands = ["commit d"]
desc = "Delete"

[[keybind]]
modes = []
keys = ["d", "w"]
commands = ["sw false", "gsb", "commit d"]
desc = "Delete Word"

[[keybind]]
modes = []
keys = ["d", "e"]
commands = ["se false", "gsb", "commit d"]
desc = "Delete Word End"

[[keybind]]
modes = []
keys = ["d", "b"]
commands = ["sb false", "gsb", "commit d"]
desc = "Delete Back Word"

[[keybind]]
modes = []
keys = ["d", "shift-w"]
commands = ["sW false", "gsb", "commit d"]
desc = "Delete WORD"

[[keybind]]
modes = []
keys = ["d", "shift-e"]
commands = ["sE false", "gsb", "commit d"]
desc = "Delete WORD End"

[[keybind]]
modes = []
keys = ["d", "shift-b"]
commands = ["sB false", "gsb", "commit d"]
desc = "Delete Back WORD"

[[keybind]]
modes = []
keys = ["d", "d"]
commands = ["sl false", "gsb", "commit d"]
desc = "Delete Line"

