[[keybind]]
modes = []
keys = [":"]
commands = ["pm c"]
desc = "Enter Command Mode"

[[keybind]]
modes = []
keys = ["i"]
commands = ["start_change", "pm i"]
desc = "Enter Insert Mode"

[[keybind]]
modes = []
keys = ["esc"]
commands = ["commit_change", "rm"]
desc = "Back To Normal Mode"
