# Basic Movement Keys
[[keybind]]
modes = []
keys = ["left"]
commands = ["move_cursor -1 0"]
desc = "Move Left"

[[keybind]]
modes = []
keys = ["down"]
commands = ["move_cursor 0 1"]
desc = "Move Down"

[[keybind]]
modes = []
keys = ["up"]
commands = ["move_cursor 0 -1"]
desc = "Move Up"

[[keybind]]
modes = []
keys = ["right"]
commands = ["move_cursor 1 0"]
desc = "Move Right"

[[keybind]]
modes = []
keys = ["h"]
commands = ["move_cursor -1 0"]
desc = "Move Left"

[[keybind]]
modes = []
keys = ["j"]
commands = ["move_cursor 0 1"]
desc = "Move Down"

[[keybind]]
modes = []
keys = ["k"]
commands = ["move_cursor 0 -1"]
desc = "Move Up"

[[keybind]]
modes = []
keys = ["l"]
commands = ["move_cursor 1 0"]
desc = "Move Right"

# Jump movements (motions)
[[keybind]]
modes = []
keys = ["w"]
commands = ["sw false", "gse", "sc"]
desc = "Go Word"

[[keybind]]
modes = []
keys = ["e"]
commands = ["se false", "gse", "sc"]
desc = "Go Word End"

[[keybind]]
modes = []
keys = ["b"]
commands = ["sb false", "gsb", "sc"]
desc = "Go Back Word"

[[keybind]]
modes = []
keys = ["shift-w"]
commands = ["sW false", "gse", "sc"]
desc = "Go WORD"

[[keybind]]
modes = []
keys = ["shift-e"]
commands = ["sE false", "gse", "sc"]
desc = "Go WORD end"

[[keybind]]
modes = []
keys = ["shift-b"]
commands = ["sB false", "gsb", "sc"]
desc = "Go Back WORD"

[[keybind]]
modes = []
keys = ["0"]
commands = ["sl false", "gsb", "sc"]
desc = "Goto Line Start"

[[keybind]]
modes = []
keys = ["$"]
commands = ["sl false", "gse", "move_cursor -1 0", "sc"]
desc = "Goto Line End"
