[[keybind]]
modes = []
keys = ["v"]
commands = ["cm v"]
desc = "Visual Mode"

[[keybind]]
modes = ["v"]
keys = ["left"]
commands = ["move_cursor -1 0 true"]
desc = "Move Left"

[[keybind]]
modes = ["v"]
keys = ["down"]
commands = ["move_cursor 0 1 true"]
desc = "Move Down"

[[keybind]]
modes = ["v"]
keys = ["up"]
commands = ["move_cursor 0 -1 true"]
desc = "Move Up"

[[keybind]]
modes = ["v"]
keys = ["right"]
commands = ["move_cursor 1 0 true"]
desc = "Move Right"

[[keybind]]
modes = ["v"]
keys = ["h"]
commands = ["move_cursor -1 0 true"]
desc = "Move Left"

[[keybind]]
modes = ["v"]
keys = ["j"]
commands = ["move_cursor 0 1 true"]
desc = "Move Down"

[[keybind]]
modes = ["v"]
keys = ["k"]
commands = ["move_cursor 0 -1 true"]
desc = "Move Up"

[[keybind]]
modes = ["v"]
keys = ["l"]
commands = ["move_cursor 1 0 true"]
desc = "Move Right"

[[keybind]]
modes = ["v"]
keys = ["w"]
commands = ["sw true", "gse"]
desc = "Select Word"

[[keybind]]
modes = ["v"]
keys = ["e"]
commands = ["se true", "gse"]
desc = "Select Word End"

[[keybind]]
modes = ["v"]
keys = ["b"]
commands = ["sb true", "gsb"]
desc = "Select Word Back"

[[keybind]]
modes = ["v"]
keys = ["shift-w"]
commands = ["sW true", "gse"]
desc = "Select WORD"

[[keybind]]
modes = ["v"]
keys = ["shift-e"]
commands = ["sE true", "gse"]
desc = "Select WORD End"

[[keybind]]
modes = ["v"]
keys = ["shift-b"]
commands = ["sB true", "gsb"]
desc = "Select WORD Back"

[[keybind]]
modes = ["v"]
keys = ["v"]
commands = ["sl true", "gse"]
desc = "Select Line"

[[keybind]]
modes = ["v"]
keys = [","]
commands = ["sc"]
desc = "Collapse Selection"

[[keybind]]
modes = ["v"]
keys = ["d"]
commands = ["gsb", "commit d", "cm n"]
desc = "Delete selection"

[[keybind]]
modes = ["v"]
keys = ["esc"]
commands = ["sc", "cm n"]
desc = "Collapse selection, enter Normal Mode"
