[package]
name = "kerbin-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.21.2"
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"
