# Themes are defined easily using palettes, which are incredibly useful
# Or if you just want something simple, you can use hexadecimal colors.
# Palette entries are also recursive, so you can have a palette entry
# Copy another palette entry if you really wanted to.
[theme]
"ts.attribute" = "yellow"

"ts.property" = "blue"
"ts.type" = "yellow"
"ts.type.enum.variant" = "teal"

"ts.constructor" = "sapphire"

"ts.constant" = "peach"
"ts.constant.character" = "teal"
"ts.constant.character.escape" = "pink"

"ts.string" = "green"
"ts.string.regexp" = "pink"
"ts.string.special" = "blue"
"ts.string.special.symbol" = "red"

"ts.comment" = { fg = "overlay2", attrs = ["italic"] }

"ts.variable" = "text"
"ts.variable.parameter" = { fg = "maroon", attrs = ["italic"] }
"ts.variable.builtin" = "red"
"ts.variable.other.member" = "blue"

"ts.label" = "sapphire" # used for lifetimes

"ts.punctuation" = "overlay2"
"ts.punctuation.special" = "sky"

"ts.keyword" = "mauve"
"ts.keyword.control.conditional" = { fg = "mauve", attrs = ["italic"] }

"ts.operator" = "sky"

"ts.function" = "blue"
"ts.function.macro" = "mauve"

"ts.tag" = "blue"

"ts.namespace" = { fg = "yellow", attrs = ["italic"] }

"ts.special" = "blue" # fuzzy highlight

"ts.text.title" = "red"
"ts.text.literal" = "peach"

"ts.markup.heading.1" = "red"
"ts.markup.heading.2" = "peach"
"ts.markup.heading.3" = "yellow"
"ts.markup.heading.4" = "green"
"ts.markup.heading.5" = "sapphire"
"ts.markup.heading.6" = "lavender"
"ts.markup.list" = "teal"
"ts.markup.list.unchecked" = "overlay2"
"ts.markup.list.checked" = "green"
"ts.markup.bold" = { fg = "red", attrs = ["bold"] }
"ts.markup.italic" = { fg = "red", attrs = ["italic"] }
"ts.markup.link.url" = { fg = "blue", attrs = ["italic", "underlined"] }
"ts.markup.link.text" = "lavender"
"ts.markup.link.label" = "sapphire"
"ts.markup.raw" = "green"
"ts.markup.quote" = "pink"

"ui.text" = "text"

"ui.linenum" = { fg = "#555555" }

"ui.commandline.valid" = { fg = "teal", attrs = ["bold"] }
"ui.commandline.invalid" = { fg = "maroon", attrs = ["bold"] }

"ui.commandline.auto_name" = { fg = "sky", attrs = ["bold", "italic"] }
"ui.commandline.primary_name" = { fg = "peach", attrs = ["bold"] }
"ui.commandline.names" = "pink"

"ui.commandline.arg_name" = "yellow"
"ui.commandline.arg_type" = { fg = "teal", attrs = ["italic"] }

"ui.commandline.desc" = { fg = "rosewater" }

"ui.commandline.border" = "blue"
"ui.commandline.title" = { fg = "mauve", attrs = ["bold"] }
"ui.commandline.prompt" = "sky"

"ui.commandline.match_highlight" = { fg = "yellow", attrs = ["bold"] }

"ui.commandline.icon" = "sky"

"ui.bufferline.selected" = { fg = "text", attrs = ["bold", "italic"] }
"ui.bufferline" = "text"

"ui.cursor" = { bg = "overlay0" }

# In the editor, rendering multicursor style is done with ui.cursor.mode0.mode1.etc
# IE: if the mode stack is nxi (default multicursor insert) you could do ui.cursor.n.x.i, 
#     or ui.cursor.x.i, or ui.cursor.i, and it would match one all three, n.x.i first.
"ui.cursor.x.i" = { bg = "green", attrs = ["bold"] }
"ui.cursor.x.v" = { bg = "sky", attrs = ["bold", "italic"] }
"ui.cursor.x" = { bg = "lavender" }
"ui.selection" = { bg = "surface1", attrs = ["italic"] }

"statusline.selections.one" = { fg = "sky", attrs = ["italic"] }
"statusline.selections.multi" = { fg = "sapphire", attrs = ["bold", "italic"] }

"statusline.mode.n" = { fg = "mantle", bg = "green", attrs = ["bold"] }
"statusline.mode.i" = { fg = "mantle", bg = "teal", attrs = ["bold"] }
"statusline.mode.c" = { fg = "mantle", bg = "maroon", attrs = ["bold"] }
"statusline.mode.x" = { fg = "mantle", bg = "lavender", attrs = ["bold"] }
"statusline.mode.v" = { fg = "mantle", bg = "pink", attrs = ["bold"] }

[plugin_config.statusline.modes]
n = { long_name = " NORMAL " }
i = { long_name = " INSERT " }
c = { long_name = " COMMAND " }
x = { long_name = " CURSOR " }
v = { long_name = " SELECT " }

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

