[package]
name = "kerbin-state-machine"
version.workspace = true
edition.workspace = true

[dependencies]
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
futures = "0.3.31"

tokio.workspace = true

tracing.workspace = true
