[package]
name = "kerbin-config"
version.workspace = true
edition.workspace = true

[dependencies]
kerbin-core.workspace = true

serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"

