// AUTO-GENERATED by booster from build.kb — do not edit manually
use kerbin_core::State;

pub async fn init(state: &mut State) {
    kerbin_lsp::init(state).await;
    kerbin_tree_sitter::init(state).await;
    tutor::init(state).await;
}
