// AUTO-GENERATED by booster from build.kb — do not edit manually
use kerbin_core::{CommandRegistry, State};

pub async fn init(state: &mut State) {
    kerbin_lsp::init(state).await;
    kerbin_tree_sitter::init(state).await;
    tutor::init(state).await;
}

pub fn register_commands(registry: &mut CommandRegistry) {
    kerbin_core::register_core_commands(registry);
    kerbin_lsp::register_commands(registry);
    kerbin_tree_sitter::register_commands(registry);
    tutor::register_commands(registry);
}
