[package]
name = "kerbin"
version.workspace = true
edition.workspace = true

[dependencies]
kerbin-core = { path = "../kerbin-core" }
kerbin-plugin = { path = "../kerbin-plugin" }

kerbin-macros.workspace = true

tokio.workspace = true

ascii-forge.workspace = true
